/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muwire_gui_MacLauncher */

#ifndef _Included_com_muwire_gui_MacLauncher
#define _Included_com_muwire_gui_MacLauncher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muwire_gui_MacLauncher
 * Method:    disableAppNap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muwire_gui_MacLauncher_disableAppNap
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
